---
- hosts: localhost
  become: true
  pre_tasks:
  - name: Update cache
    ansible.builtin.homebrew:
      update_homebrew: yes
    become: no
    tags:
    - node
    - deno
    - zsh
    - bun
    - git
    - util
  tasks:
  - include: ansible-tasks/zsh.yml
  - include: ansible-tasks/node.yml
  - include: ansible-tasks/git.yml
  - include: ansible-tasks/util.yml

  - name: Install deno
    shell: brew install deno
    become: no
    tags:
    - deno

  - name: Install bun
    shell: curl -fsSL https://bun.sh/install | bash
    tags:
    - bun

  - name: Install Rust tools
    shell: brew install rustup-init
    become: no
    tags:
    - rust
