---
- hosts: localhost
  pre_tasks:
  - name: Include tasks for detected package manager
    include_tasks: "{{ item }}"
    with_first_found:
      - files:
          - "ansible-tasks/pmg/update_cache_{{ ansible_pkg_mgr }}.yml"
        paths:
          - ./
    loop_control:
      loop_var: item
    tags:
    - bun
    - deno
    - git
    - node
    - rust
    - util
    - zig
    - zsh
  tasks:
  - include: ansible-tasks/zsh.yml
  - include: ansible-tasks/util.yml
  - include: ansible-tasks/git.yml
  - include: ansible-tasks/docker.yml
  - include: ansible-tasks/node.yml
  - include: ansible-tasks/deno.yml
  - include: ansible-tasks/bun.yml
  - include: ansible-tasks/rust.yml
  - include: ansible-tasks/zig.yml
  - include: ansible-tasks/golang.yml