---
- hosts: localhost
# Become needs to be false, opt in to become manually in tasks
  become: false
  name: RATIU5' Ansible Playbook
  pre_tasks:
    - name: Update homebrew (macOS)
      when: "'Darwin' in ansible_system"
      become: false
      community.general.homebrew:
        update_homebrew: true
  vars:
    user: "{{ ansible_env.USER }}"
    home: "{{ ansible_env.HOME }}"
    config_dir: "{{ home }}/.config"
    cache_dir: "{{ home }}/.cache"
    data_dir: "{{ home }}/.local/share"
    bin_dir: "{{ home }}/.local/bin"
    dev_dir: "{{ home }}/Developer"
    zshrc: "{{ config_dir }}/zsh/.zshrc"
    dotfile_repo: "https://github.com/RATIU5/dotfiles.git"
    dotfile_name: "dotfiles"
  tasks:
    - name: "Directories"
      ansible.builtin.import_tasks: tasks/dirs.yml
    - name: "dotfiles"
      ansible.builtin.import_tasks: tasks/dotfiles.yml
    - name: "Terminal"
      ansible.builtin.import_tasks: tasks/terminal.yml
    - name: "Aliases"
      ansible.builtin.import_tasks: tasks/alias.yml
    - name: "Settings"
      ansible.builtin.import_tasks: tasks/settings.yml
    - name: Install Window Management
      ansible.builtin.import_tasks: tasks/windows.yml
    - name: "Install languages"
      ansible.builtin.import_tasks: tasks/lang.yml
    # - name: Install Cask apps
    #   ansible.builtin.import_tasks: tasks/caskapps.yml
    # - name: Install App Store apps
    #   ansible.builtin.import_tasks: tasks/macapps.yml
