---
- hosts: localhost
  pre_tasks:
    - name: Update the package manager (Linux)
      when: "'Linux' in ansible_system"
      become: false
      package:
        update_cache: true
        state: present
    - name: Update homebrew (macOS)
      when: "'Darwin' in ansible_system"
      become: false
      homebrew:
        update_homebrew: yes
      tags:
        - init
  vars:
    CONFIG_DIR: "{{ ansible_env.HOME }}/.config"
    zshrc: "{{ CONFIG_DIR }}/zsh/.zshrc"
  tasks:
    - include: tasks/init.ansibe.yml
    - include: tasks/alias.ansibe.yml
    # - include: tasks/zsh.ansibe.yml
    # - include: tasks/tmux.ansibe.yml
    # - include: tasks/util.ansibe.yml
    # - include: tasks/git.ansibe.yml
    # - include: tasks/docker.ansibe.yml
    # - include: tasks/node.ansibe.yml
    # - include: tasks/deno.ansibe.yml
    # - include: tasks/bun.ansibe.yml
    # - include: tasks/rust.ansibe.yml
    # - include: tasks/zig.ansibe.yml
    # - include: tasks/golang.ansibe.yml
