---
- hosts: localhost
  become: true
  pre_tasks:
  - name: Update cache
    ansible.builtin.homebrew:
      update_homebrew: yes
    become: no
    tags:
    - bun
    - deno
    - git
    - node
    - rust
    - util
    - zig
    - zsh
  tasks:
  - include: ansible-tasks/zsh.yml
  - include: ansible-tasks/util.yml
  - include: ansible-tasks/git.yml
  - include: ansible-tasks/docker.yml
  - include: ansible-tasks/node.yml
  - include: ansible-tasks/deno.yml
  - include: ansible-tasks/bun.yml
  - include: ansible-tasks/rust.yml
  - include: ansible-tasks/zig.yml
  - include: ansible-tasks/golang.yml