- name: Tap into the bun repo
  community.general.homebrew_tap:
    name: oven-sh/bun
    state: present
  become: false
  become_user: "{{ user }}"
  tags:
    - bun

- name: Install bun
  community.general.homebrew:
    name: bun
    state: present
  become: false
  become_user: "{{ user }}"
  tags:
    - bun
