- name: Install cask apps
  when: "'Darwin' in ansible_system"
  tags:
    - caskapps
  block:
    - name: Install Discord
      community.general.homebrew_cask:
        name: discord
        state: present
      ignore_errors: true
      become: false
      become_user: "{{ user }}"

    - name: Install Slack
      community.general.homebrew_cask:
        name: slack
        state: present
      ignore_errors: true
      become: false
      become_user: "{{ user }}"

    - name: Install Spotify
      community.general.homebrew_cask:
        name: spotify
        state: present
      ignore_errors: true
      become: false
      become_user: "{{ user }}"

    - name: Install Docker
      community.general.homebrew_cask:
        name: docker
        state: present
      ignore_errors: true
      become: false
      become_user: "{{ user }}"

    - name: Install Raindrop.io
      community.general.homebrew_cask:
        name: raindropio
        state: present
      ignore_errors: true
      become: false
      become_user: "{{ user }}"

    - name: Install AppCleaner
      community.general.homebrew_cask:
        name: appcleaner
        state: present
      ignore_errors: true
      become: false
      become_user: "{{ user }}"

    - name: Install the Unarchiver
      community.general.homebrew_cask:
        name: the-unarchiver
        state: present
      ignore_errors: true
      become: false
      become_user: "{{ user }}"

    - name: Install Radio Silence
      community.general.homebrew_cask:
        name: radio-silence
        state: present
      ignore_errors: true
      become: false
      become_user: "{{ user }}"

    - name: Install 1Password
      community.general.homebrew_cask:
        name: 1password
        state: present
      ignore_errors: true
      become: false
      become_user: "{{ user }}"

    - name: Install Alfred
      community.general.homebrew_cask:
        name: alfred
        state: present
      ignore_errors: true
      become: false
      become_user: "{{ user }}"

    - name: Install Alacritty
      community.general.homebrew_cask:
        name: alacritty
        state: present
      ignore_errors: true
      become: false
      become_user: "{{ user }}"

    - name: Install Arc Browser
      community.general.homebrew_cask:
        name: arc
        state: present
      ignore_errors: true
      become: false
      become_user: "{{ user }}"

    # - name: Install OBS
    #   community.general.homebrew_cask:
    #     name: obs
    #     state: present
    #   become: false
    #   become_user: "{{ user }}"
