- name: Install Docker using Homebrew (macOS)
  homebrew:
    name: docker
    state: present
  when: "'Darwin' in ansible_system"
  become: no
  tags:
    - docker

- name: Install Docker using package manager (Linux)
  package:
    name: docker
    state: present
  when: "'Linux' in ansible_system"
  tags:
    - docker
