- name: Install Docker using Homebrew (macOS)
  community.general.homebrew:
    name: docker
    state: present
  tags:
    - docker

- name: Set docker daemon config
  block:
    - name: Ensure /etc/docker exists
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        mode: "0o755"
      tags:
        - docker

    - name: Ensure /etc/docker/daemon.json exists
      ansible.builtin.file:
        path: /etc/docker/daemon.json
        state: touch
        mode: "0o755"
      tags:
        - docker
    - name: Set the data-root config
      ansible.builtin.lineinfile:
        path: /etc/docker/daemon.json
        line: '{"data-root": "{{ config_dir }}/docker"}'
        state: present
        insertafter: EOF
        create: true
        mode: "0o755"
      tags:
        - docker
