- name: "Setup dotfiles"
  block:
    - name: "Install GNU Stow via Homebrew"
      community.general.homebrew:
        name: stow
        state: present
      become: false
      become_user: "{{ user }}"
    - name: Check if the {{ dev_dir }}/{{ dotfile_name }} directory exists
      stat:
        path: "{{ dev_dir }}/{{ dotfile_name }}"
      register: git_clone_directory
    - name: "Clone {{ dotfile_name }} from GitHub"
      ansible.builtin.git:
        repo: "{{ dotfile_repo }}"
        dest: "{{ dev_dir }}"
      when: not git_clone_directory.stat.exists
    - name: "Stow {{ dotfile_name }} to {{ config_dir }}"
      ansible.builtin.shell:
        cmd: "stow -t {{ config_dir }} {{ dotfile_name }}"
        chdir: "{{ dev_dir }}"
  tags:
    - dotfiles