
- name: Install git using Homebrew (macOS)
  homebrew:
    name: git
    state: present
  when: "'Darwin' in ansible_system"
  become: no
  tags:
    - git

- name: Install git using apt (Linux)
  package:
    name: git
    state: present
  when: "'Linux' in ansible_system"
  become: yes
  tags:
    - git

- name: Git configuration
  command: "{{ item.cmd }}"
  environment:
    GIT_CONFIG: "{{ ansible_env.HOME }}/.config/git/.gitconfig"
  loop:
    - { cmd: "git config user.name 'RATIU5'", name: 'user.name', value: 'RATIU5' }
    - { cmd: "git config user.email 'jcmemmott20@outlook.com'", name: 'user.email', value: 'jcmemmott20@outlook.com' }
  tags:
    - git