- name: Setup git
  tags:
    - git
  block:
    - name: Git config folder exists
      ansible.builtin.file:
        path: "{{ git_dir }}"
        state: directory
        mode: "0o755"

    - name: Git config file exists
      ansible.builtin.file:
        path: "{{ git_dir }}/config"
        state: touch
        mode: "0o755"

    - name: Set git config username
      community.general.git_config:
        scope: global
        name: user.name
        value: "{{ git_user_name }}"
        file: "{{ git_dir }}/config"

    - name: Set git config email
      community.general.git_config:
        scope: global
        name: user.email
        value: "{{ git_user_email }}"
        file: "{{ git_dir }}/config"
