- name: Setup git
  tags:
    - git
  block:
    - name: Git config folder exists
      ansible.builtin.file:
        path: "{{ git_dir }}"
        state: directory
        mode: "0o755"

    - name: Git config file exists
      ansible.builtin.file:
        path: "{{ git_dir }}/config"
        state: touch
        mode: "0o755"

    - name: Set git config username
      ansible.builtin.shell:
        cmd: git config --file "{{ git_dir }}/config" user.name "{{ git_user_name }}"

    - name: Set git config email
      ansible.builtin.shell:
        cmd: git config --file "{{ git_dir }}/config" user.email "{{ git_user_email }}"
