- name: Install git (macOS)
  homebrew:
    name: git
    state: present
  when: "'Darwin' in ansible_system"
  become: no
  tags:
    - git

- name: Install gh (macOS)
  homebrew:
    name: gh
    state: present
  when: "'Darwin' in ansible_system"
  become: no
  tags:
    - git

- name: Install git (Linux)
  package:
    name: git
    state: present
  when: "'Linux' in ansible_system"
  become: yes
  tags:
    - git

- name: Install gh (Linux)
  package:
    name: gh
    state: present
  when: "'Linux' in ansible_system"
  become: yes
  tags:
    - git

- name: Git configuration (Linux & MacOS)
  command: "{{ item.cmd }}"
  environment:
    GIT_CONFIG: "{{ ansible_env.HOME }}/.config/git/config"
  loop:
    - {
        cmd: "git config user.name 'RATIU5'",
        name: "user.name",
        value: "RATIU5",
      }
    - {
        cmd: "git config user.email 'jcmemmott20@outlook.com'",
        name: "user.email",
        value: "jcmemmott20@outlook.com",
      }
  tags:
    - git
