# structure setup

- name: Ensure {{ ansible.env.HOME }}/.zshenv file exists
  file:
    path: "{{ ansible_env.HOME }}/.zshenv"
    state: touch
  tags:
    - init

- name: Ensure .zshenv has the location of the .zshrc file
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshenv"
    line: 'export ZDOTDIR="{{ CONFIG_DIR }}/zsh"'
    state: present
    insertafter: EOF
    create: yes
  tags:
    - init

- name: Ensure {{ CONFIG_DIR }} directory exists
  file:
    path: "{{ CONFIG_DIR }}"
    state: directory
  tags:
    - init

- name: Ensure {{ CONFIG_DIR }}/zsh directory exists
  file:
    path: "{{ CONFIG_DIR }}/zsh"
    state: directory
  tags:
    - init

- name: Ensure {{ CONFIG_DIR }}/zsh/.zshrc file exists
  file:
    path: "{{ CONFIG_DIR }}/zsh/.zshrc"
    state: touch
  tags:
    - init

# zsh setup

- name: Ensure zsh is installed
  homebrew:
    name: zsh
    state: present
  tags:
    - init

- name: Ensure zsh-autosuggestions is installed
  homebrew:
    name: zsh-autosuggestions
    state: present
  tags:
    - init

- name: Source zsh-autosuggestions
  lineinfile:
    path: "{{ zshrc }}"
    line: 'source {{ HOMEBREW_PREFIX }}/share/zsh-autosuggestions/zsh-autosuggestions.zsh'
    state: present
    insertafter: EOF
    create: yes
  tags:
    - init

- name: Skip global compinit
  when: "'Linux' in ansible_system"
  lineinfile:
    path: "{{ zshrc }}"
    line: 'skip_global_compinit=1'
    state: present
    insertafter: EOF
    create: yes
  tags:
    - init

- name: Configure homebrew
  lineinfile:
    path: "{{ zshrc }}"
    line: 'eval "$({{ HOMEBREW_PREFIX }}/bin/brew shellenv)"'
    state: present
    insertafter: EOF
    create: yes
  tags:
    - init

- name: Eval brew shellenv
  shell: 'eval "$({{ HOMEBREW_PREFIX }}/bin/brew shellenv)"'
  args:
    executable: /bin/zsh
  tags:
    - init