# structure setup

- name: "Create directory structure"
  block:
    - name: Ensure ~/.zshenv file exists
      ansible.builtin.file:
        path: "{{ home }}/.zshenv"
        state: touch
        mode: "0o755"
      tags:
        - init

    - name: Ensure ~/.config directory exists
      ansible.builtin.file:
        path: "{{ config_dir }}"
        state: directory
        mode: "0o755"
      tags:
        - init

    - name: Ensure ~/.config/zsh directory exists
      ansible.builtin.file:
        path: "{{ config_dir }}/zsh"
        state: directory
        mode: "0o755"
      tags:
        - init

    - name: Ensure ~/.config/zsh/.zshrc file exists
      ansible.builtin.file:
        path: "{{ config_dir }}/zsh/.zshrc"
        state: touch
        mode: "0o755"
      tags:
        - init

# environment variables

- name: "Set environment variables"
  block:
    - name: Ensure ~/.zshenv has XDG_CONFIG_HOME set
      ansible.builtin.lineinfile:
        path: "{{ home }}/.zshenv"
        line: 'export XDG_CONFIG_HOME="{{ config_dir }}"'
        state: present
        insertafter: EOF
        create: true
        mode: "0o755"
      tags:
        - init

    - name: Ensure .zshenv has the location of the .zshrc file
      ansible.builtin.lineinfile:
        path: "{{ home }}/.zshenv"
        line: 'export ZDOTDIR="{{ config_dir }}/zsh"'
        state: present
        insertafter: EOF
        create: true
        mode: "0o755"
      tags:
        - init

# zsh setup

- name: Install zsh if it's not already installed
  tags:
    - init
  block:
    - name: Check if zsh is installed
      ansible.builtin.shell: which zsh
      register: zsh_installed
      ignore_errors: true

    - name: Install zsh
      community.general.homebrew:
        name: zsh
        state: present
      when: zsh_installed.rc != 0

- name: Set zsh as the default shell
  tags:
    - init
  block:
    - name: Retrieve shell path
      ansible.builtin.shell: echo $SHELL
      register: shell

    - name: Retrieve zsh path
      ansible.builtin.shell: which zsh
      register: zsh_path

    - name: Set zsh as the default shell
      ansible.builtin.shell: chsh -s "{{ zsh_path.stdout }}"
      when: shell.stdout != zsh_path.stdout

- name: Configure homebrew
  block:
    - name: Skip global compinit (for homebrew on Linux)
      when: "'Linux' in ansible_system"
      ansible.builtin.lineinfile:
        path: "{{ zshrc }}"
        line: "skip_global_compinit=1"
        state: present
        insertafter: EOF
        create: true
        mode: "0o755"
      tags:
        - init

    - name: Add homebrew to path
      ansible.builtin.lineinfile:
        path: "{{ zshrc }}"
        line: 'eval "$({{ homebrew_prefix }}/bin/brew shellenv)"'
        state: present
        insertafter: EOF
        create: true
        mode: "0o755"
      tags:
        - init

    - name: Eval brew shellenv
      ansible.builtin.shell: 'eval "$({{ homebrew_prefix }}/bin/brew shellenv)"'
      tags:
        - init

- name: Install zsh-autosuggestions
  tags:
    - init
  block:
    - name: Install zsh-autosuggestions via homebrew
      community.general.homebrew:
        name: zsh-autosuggestions
        state: present

    - name: Source zsh-autosuggestions
      ansible.builtin.lineinfile:
        path: "{{ zshrc }}"
        line: "source {{ homebrew_prefix }}/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
        state: present
        insertafter: EOF
        create: true
        mode: "0o755"

- name: Install starship
  tags:
    - init
  block:
    - name: Install starship via homebrew
      community.general.homebrew:
        name: starship
        state: present

    - name: Add starship to zshrc
      ansible.builtin.lineinfile:
        path: "{{ zshrc }}"
        line: 'eval "$(starship init zsh)"'
        state: present
        create: true
        mode: "0o755"

- name: Setup Yabai window tiling manager
  when: "'Darwin' in ansible_system"
  tags:
    - init
  block:
    - name: Install yabai via homebrew
      community.general.homebrew:
        name: koekeishiya/formulae/yabai
        state: present

    - name: Start yabai
      ansible.builtin.shell: yabai --start-service
