- name: Install n node version manager
  community.general.homebrew:
    name: n
    state: present
  become: false
  become_user: "{{ user }}"
  tags:
    - node

- name: Install Node.js version 16
  ansible.builtin.shell: n 16
  become: true
  become_user: "{{ user }}"
  tags:
    - node

- name: Configure npm cache directory
  shell: |
    source "$(which n)"
    npm config set cache {{ cache_dir }}/npm
  become: false
  become_user: "{{ user }}"
  tags:
    - node
