- name: Download n node version manager (Linux)
  when: "'Linux' in ansible_system"
  get_url:
    url: https://raw.githubusercontent.com/tj/n/master/bin/n
    dest: /usr/local/bin/n
    mode: "0755" # make the script executable
  tags:
    - node

- name: Create n version folder
  when: "'Linux' in ansible_system"
  file:
    path: /usr/local/n/versions
    state: directory
  become: yes
  tags:
    - node

- name: Install n node version manager (macOS)
  when: "'Darwin' in ansible_system"
  homebrew:
    name: n
    state: present
  become: no
  tags:
    - node

- name: Install Node.js version 20
  when: "'Linux' in ansible_system"
  command:
    cmd: n 20
  become: yes
  tags:
    - node
