- name: Install n node version manager
  community.general.homebrew:
    name: n
    state: present
  become: false
  tags:
    - node

- name: Install Node.js version 16
  ansible.builtin.shell: n 16
  tags:
    - node

- name: Configure npm cache directory
  ansible.builtin.shell: npm config set cache {{ cache_dir }}/npm --global
  tags:
    - node
