- name: Download n node version manager (Linux)
  when: "'Linux' in ansible_system"
  get_url:
    url: https://raw.githubusercontent.com/tj/n/master/bin/n
    dest: /tmp/n-install
    mode: "0755" # make the script executable
  tags:
    - node

- name: Create n version folder
  when: "'Linux' in ansible_system"
  command:
    cmd: mkdir -p /usr/local/n/versions
  become: yes
  tags:
    - node

- name: Install n node version manager (Linux)
  when: "'Linux' in ansible_system"
  command:
    cmd: /tmp/n-install
  become: yes
  tags:
    - node

- name: Install n node version manager (macOS)
  when: "'Darwin' in ansible_system"
  homebrew:
    name: n
    state: present
  become: no
  tags:
    - node

- name: n 20
  command:
    cmd: n 20
  tags:
    - node
