- name: Set general settings (mac)
  when: '"Darwin" in ansible_system'
  block:
    - name: Set Dock to auto-hide
      ansible.builtin.shell: defaults write com.apple.dock autohide -bool true
      become_user: "{{ user }}"
      become: true
      tags:
        - settings
    - name: Set Dock delay to 0
      ansible.builtin.shell: defaults write com.apple.dock autohide-delay -float 0
      become_user: "{{ user }}"
      become: true
      tags:
        - settings
    - name: Set Dock animation to 0
      ansible.builtin.shell: defaults write com.apple.dock autohide-time-modifier -float 0
      become_user: "{{ user }}"
      become: true
      tags:
        - settings
    - name: Set Dock size
      ansible.builtin.shell: defaults write com.apple.dock tilesize -int 100
      become_user: "{{ user }}"
      become: true
      tags:
        - settings
    - name: Restart Dock
      ansible.builtin.shell: killall Dock
      become_user: "{{ user }}"
      become: true
      tags:
        - settings
    - name: Show hidden files
      ansible.builtin.shell: defaults write com.apple.finder AppleShowAllFiles YES
      become_user: "{{ user }}"
      become: true
      tags:
        - settings
    - name: Show path bar
      ansible.builtin.shell: defaults write com.apple.finder ShowPathbar -bool true
      become_user: "{{ user }}"
      become: true
      tags:
        - settings
    - name: Show status bar
      ansible.builtin.shell: defaults write com.apple.finder ShowStatusBar -bool true
      become_user: "{{ user }}"
      become: true
      tags:
        - settings
    - name: Show all filename extensions
      ansible.builtin.shell: defaults write NSGlobalDomain AppleShowAllExtensions -bool true
      become_user: "{{ user }}"
      become: true
      tags:
        - settings
    - name: Disable the warning when changing a file extension
      ansible.builtin.shell: defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
      become_user: "{{ user }}"
      become: true
      tags:
        - settings
    - name: Disable iCloud in Finder
      ansible.builtin.shell: defaults write com.apple.finder FXICloudDriveEnabled -bool false
      become_user: "{{ user }}"
      become: true
      tags:
        - settings
