- name: zsh setup
  block:
    - name: Check if zsh is installed
      ansible.builtin.shell: which zsh
      register: zsh_installed
      ignore_errors: true

    - name: Install zsh
      community.general.homebrew:
        name: zsh
        state: present
      become: false
      when: zsh_installed.rc != 0
  tags:
    - terminal
    - zsh

- name: Set zsh as the default shell
  block:
    - name: Retrieve shell path
      ansible.builtin.shell: echo $SHELL
      register: shell

    - name: Retrieve zsh path
      ansible.builtin.shell: which zsh
      register: zsh_path

    - name: Set zsh as the default shell
      ansible.builtin.shell: chsh -s "{{ zsh_path.stdout }}"
      when: shell.stdout != zsh_path.stdout
  tags:
    - terminal
    - zsh

- name: Install zsh-autosuggestions via homebrew
  community.general.homebrew:
    name: zsh-autosuggestions
    state: present
  become: false
  tags:
    - terminal
    - zsh

- name: Install starship via homebrew
  community.general.homebrew:
    name: starship
    state: present
  become: false
  tags:
    - terminal
    - starship

- name: Install tmux
  community.general.homebrew:
    name: tmux
    state: present
  become: false
  tags:
    - terminal
    - tmux

- name: Configure tmux
  ansible.builtin.shell: "tmux -f {{ config_dir }}/tmux/.tmux.conf"
  ignore_errors: true
  tags:
    - terminal
    - tmux

- name: Install bat as a cat replacement
  community.general.homebrew:
    name: bat
    state: present
  become: false
  tags:
    - terminal
    - bat

- name: Install fzf
  community.general.homebrew:
    name: fzf
    state: present
  become: false
  tags:
    - terminal
    - fzf

- name: Setup fzf
  ansible.builtin.shell: $(brew --prefix)/opt/fzf/install
  ignore_errors: true
  tags:
    - terminal
    - fzf

- name: Install ripgrep, replacement for grep
  community.general.homebrew:
    name: ripgrep
    state: present
  become: false
  tags:
    - terminal
    - ripgrep

- name: Install fd, replacement for find
  community.general.homebrew:
    name: fd
    state: present
  become: false
  tags:
    - terminal
    - fd

- name: Install eza, replacement for ls
  community.general.homebrew:
    name: eza
    state: present
  become: false
  tags:
    - terminal
    - eza

- name: Install neovim
  community.general.homebrew:
    name: neovim
    state: present
  become: false
  tags:
    - terminal
    - nvim

- name: Fonts
  block:
    - name: Tap homebrew/cask-fonts
      community.general.homebrew_tap:
        name: homebrew/cask-fonts
        state: present
      become: false
      become_user: "{{ user }}"

    - name: Install font-jetbrains-mono-nerd-font via Homebrew
      community.general.homebrew:
        name: font-jetbrains-mono-nerd-font
        state: present
      ignore_errors: true
  tags:
    - terminal
    - fonts
