- name: Install tmux (Linux)
  when: "'Linux' in ansible_system"
  package:
    name: tmux
    state: present
  become: yes
  tags:
    - tmux

- name: Install tmux (macOS)
  when: "'Darwin' in ansible_system"
  homebrew:
    name: tmux
    state: present
  become: no
  tags:
    - tmux
