- name: Install ripgrep
  homebrew:
    name: ripgrep
    state: present
  become: false
  become_user: "{{ user }}"
  tags:
    - util

- name: Install stow
  homebrew:
    name: stow
    state: present
  become: false
  become_user: "{{ user }}"
  tags:
    - util
