- name: Check if ZSH is installed
  command: which zsh
  register: zsh_installed
  ignore_errors: yes
  tags:
    - zsh

- name: Install ZSH
  package:
    name: ZSH
    state: present
  when: zsh_installed.rc != 0
  tags:
    - zsh

- name: Check if ZSH is the default shell (Linux)
  command: "getent passwd {{ ansible_env.USER }} | awk -F: '{ print $7 }'"
  register: user_shell
  changed_when: False
  ignore_errors: true
  when: "'Darwin' not in ansible_system"
  tags:
    - zsh

- name: Check if ZSH is the default shell (macOS)
  command: "dscl . -read /Users/{{ ansible_env.USER }} UserShell"
  register: user_shell_mac
  changed_when: False
  ignore_errors: true
  when: "'Darwin' in ansible_system"
  tags:
    - zsh

- name: Set ZSH as the default shell (Linux)
  command: "chsh -s $(which zsh)"
  when: "user_shell.stdout is defined and '/usr/bin/zsh' != user_shell.stdout and 'Darwin' not in ansible_system"
  tags:
    - zsh

- name: Set ZSH as the default shell (macOS)
  command: "chsh -s /bin/zsh"
  when: "'/bin/zsh' not in user_shell_mac.stdout and 'Darwin' in ansible_system"
  tags:
    - zsh

- name: Download ZSH plugin autosuggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "$XDG_CONFIG_HOME/zsh/zsh-autosuggestions"
  tags:
    - zsh

- name: Install autosuggestions to ZSH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.config/zsh/.zshrc"
    line: "source $XDG_CONFIG_HOME/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"
    state: present
    create: yes
  tags:
    - zsh

- name: Install Starship
  shell: brew install starship
  become: no
  tags:
    - zsh

- name: Add starship to zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.config/zsh/.zshrc"
    line: 'eval "$(starship init zsh)"'
    state: present
    create: yes
  tags:
    - zsh
