- name: Check if zsh is installed
  command: which zsh
  register: zsh_installed
  ignore_errors: yes
  tags:
    - zsh

- name: Install zsh
  package:
    name: zsh
    state: present
  when: zsh_installed.rc != 0
  tags:
    - zsh

- name: Check if zsh is the default shell (Linux)
  command: "getent passwd {{ ansible_env.USER }} | awk -F: '{ print $7 }'"
  register: user_shell
  changed_when: False
  ignore_errors: true
  when: "'Linux' in ansible_system"
  tags:
    - zsh

- name: Check if zsh is the default shell (macOS)
  command: "dscl . -read /Users/{{ ansible_env.USER }} UserShell"
  register: user_shell_mac
  changed_when: False
  ignore_errors: true
  when: "'Darwin' in ansible_system"
  tags:
    - zsh

- name: Set zsh as the default shell (Linux)
  command: "chsh -s $(which zsh)"
  when: "'Linux' in ansible_system and user_shell.stdout is defined and '/usr/bin/zsh' != user_shell.stdout"
  tags:
    - zsh

- name: Set zsh as the default shell (macOS)
  command: "chsh -s /bin/zsh"
  when: "'Darwin' in ansible_system and '/bin/zsh' not in user_shell_mac.stdout"
  tags:
    - zsh

- name: Download zsh plugin autosuggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ ansible_env.HOME }}/.config/zsh/zsh-autosuggestions"
  tags:
    - zsh

- name: Install autosuggestions to zsh
  lineinfile:
    path: "{{ ansible_env.HOME }}/.config/zsh/.zshrc"
    line: source ~/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
    state: present
    create: yes
  tags:
    - zsh

- name: Install Starship (Linux)
  when: "'Linux' in ansible_system"
  shell: DEBIAN_FRONTEND=noninteractive curl -fsSL https://starship.rs/install.sh | sh -s -- -y
  become: yes
  tags:
    - zsh

- name: Install Starship (macOS)
  when: "'Darwin' in ansible_system"
  shell: brew install starship
  become: no
  tags:
    - zsh

- name: Add starship to zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.config/zsh/.zshrc"
    line: 'eval "$(starship init zsh)"'
    state: present
    create: yes
  tags:
    - zsh
