- name: Set Deno environment variables
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshenv"
    line: 'export {{ item }}'
    create: yes
  with_items:
    - 'DENO_DIR="{{ ansible_env.HOME }}/.config/deno"'
    - 'PATH="$DENO_DIR/bin:$PATH"'
  tags:
    - deno

- name: Install Deno using Homebrew (macOS)
  shell: curl -fsSL https://deno.land/x/install/install.sh | sh
  tags:
    - deno