- name: Install Rust tools
  homebrew:
    name: go
    state: present
  become: no
  tags:
    - rust

- name: Ensure ~/.config/cargo directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/cargo"
    state: directory
  become: no
  tags:
    - rust

- name: Move .cargo to .config/cargo if it exists
  ansible.builtin.command:
    cmd: "mv {{ ansible_env.HOME }}/.cargo/* {{ ansible_env.HOME }}/.config/cargo/"
  args:
    removes: "{{ ansible_env.HOME }}/.cargo/"
  become: no
  ignore_errors: yes
  tags:
    - rust

- name: Add .cargo environment variables to .zshenv
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshenv"
    line: "export CARGO_HOME={{ ansible_env.HOME }}/.config/cargo"
    state: present
    create: yes
  become: no
  tags:
    - rust